#!/usr/bin/python3
print("Programmin    g is like building a multilingual puzzle,\n")
                     
                     
                     
                     
                     
                     
                     
                     
                     
                     
                     
                     
                     
                     
                     
                     
                     
                     
                     
                     
                     
                     
                     
                     
                     
                     
                     
                     
                     
                     
                     
                     
                     
                     
                 
                     
                     
                     
                 
                     
                     
                     
                     
                     
                     
                     
                     
                     
    
    
